### ISSUE TITLE
Table.save throwing exception trying to save object

### ISSUE THREAD

**Issue by matheo** [robconery/massive-js#122]
Hi all! First, thanks for this great lib!

I'm starting with Massive as it looks super cool to keep my apps on the top of my loved postgres, but I'm having some issues setting up a first app using it. I have a table named "eventos" with 6 columns [id (pk), titulo (not null), fecha, tipo, empleado, obs] and I'm trying to save an object through `POST /eventos` with:
```
curl --data 'titulo=Entrada&fecha=144102924600' http://localhost:3000/eventos
```

## My node app
app.js
```
var app = express();

var massive = require("massive");
var connectionString = "postgres://user:pass@localhost/mydb";
var massiveInstance = massive.connectSync({connectionString : connectionString});
app.set('db', massiveInstance);

var routes = require('./routes/index');
...
```
routes/index.js
```
router.post('/eventos', function(req, res, next) {
  var db = req.app.get('db');

  db.eventos.save(req.body, function(err, event){
    if(err){ return next(err); }
    res.json(event);
  });
});
```

### First Exception
```
<h1>array value must start with &#34;{&#34; or dimension information</h1>
<h2></h2>
<pre>Error: array value must start with &#34;{&#34; or dimension information
    at DB.query (/events/node_modules/massive/lib/runner.js:17:11)
    at Table.insert (/events/node_modules/massive/lib/table.js:38:11)
    at Table.save (/events/node_modules/massive/lib/table.js:107:10)
    at /events/routes/index.js:21:14
    at Layer.handle [as handle_request] (/events/node_modules/express/lib/router/layer.js:95:5)
    at next (/events/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/events/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/events/node_modules/express/lib/router/layer.js:95:5)
    at /events/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/events/node_modules/express/lib/router/index.js:330:12)</pre>
```
so I "jsonify" the input data and try again:

### Second Exception
so I change the input data like:
```
router.post('/eventos', function(req, res, next) {
  var db = req.app.get('db');

  rec = JSON.stringify(req.body);

  db.eventos.save(rec, function(err, event){
    if(err){ return next(err); }
    res.json(event);
  });
});
```

and trying again I get a new one:
```
<h1>Please pass in the criteria for saving as an object. This should include all fields needed to change or add. Include the primary key for an UPDATE.</h1>
<h2></h2>
<pre>AssertionError: Please pass in the criteria for saving as an object. This should include all fields needed to change or add. Include the primary key for an UPDATE.
    at Table.save (/events/node_modules/massive/lib/table.js:102:3)
    at /events/routes/index.js:21:14
    at Layer.handle [as handle_request] (/events/node_modules/express/lib/router/layer.js:95:5)
    at next (/events/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/events/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/events/node_modules/express/lib/router/layer.js:95:5)
    at /events/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/events/node_modules/express/lib/router/index.js:330:12)
    at next (/events/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/events/node_modules/express/lib/router/index.js:176:3)</pre>
```

What's happening? how can I make this work?
Thanks in advance!

**Comment by xivSolutions** [comment]
What are you getting back as the request body that you are then trying to save after stringify? Maybe output to the console and share? Do the object properties match the table columns?

**Comment by matheo** [comment]
`req.body` is going as expected, I didn't mention my `console.log(req.body)` here. In the first case, the object is fine: 
```
{ titulo: 'Entrada', fecha: '144102924600' }
```
and when I jsonify it goes well too:
```
{"titulo":"Entrada","fecha":"144102924600"}
```
not even hardcoding the record like:
```
db.eventos.save({titulo:'Entrada',fecha:'144102924600'}', function(err, event){
    if(err){ return next(err); }

    res.json(event);
  });
```
I have to specify all the table fields? it's supposed to be not required right?

**Comment by matheo** [comment]
For the record, here is my spec:
```
Ubuntu 14.04.3 LTS
npm 2.14.2
node v4.0.0
massive 2.0.9
express 4.13.1
```

**Comment by xivSolutions** [comment]
Hmm. No, you shouldn't have to match all the fields. Does your table have a serial int id column?

**Comment by matheo** [comment]
Wooot, that was the problem.
Mistakes in the table definition all around! the first exception (`array value must start with &#34;{&#34; or dimension information`) was because my field was an array, that was an accident.

Now the `save` runs smootly.
Thank you very much!
