### ISSUE TITLE
SSL Database Connection.

### ISSUE THREAD

**Issue by aderbas** [robconery/massive-js#136]
My database manager does not allow connections outside of SSL, in pg_hba.conf file contains no entry "host" all are "hostssl" and I'm not allowed to change it on the production server. 

```error: no pg_hba.conf entry for host "127.0.0.1", user "foo", database "fooserver", SSL off```

Any idea how to make that connection with ssl?
(I do not know if I was clear)

**Comment by robconery** [comment]
Is Massive throwing an error?

**Comment by aderbas** [comment]
```
/var/www/mobileapi/lib/node_modules/massive/node_modules/deasync/index.js:38
			throw err;
			      ^
error: no pg_hba.conf entry for host "127.0.0.1", user "foo", database "fooserver", SSL off
    at Connection.parseE (/var/www/mobileapi/lib/node_modules/massive/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/www/mobileapi/lib/node_modules/massive/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/www/mobileapi/lib/node_modules/massive/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

**Comment by robconery** [comment]
I'm thinking this is a Postgres error...

**Comment by aderbas** [comment]
Yes, but why not accept any connection from an unsafe environment, no SSL connections. There is no way to make this connection even the script running on the same machine as the database.

**Comment by robconery** [comment]
I'm sorry I just don't understand what it is you want here. If you look through the stack trace Massive is simply trying to connect. The `pg` library does it's thing and and boom - Postgres doesn't like it.

I don't think Massive is throwing this error - Postgres is.

**Comment by aderbas** [comment]
Ops, I'm have added ```?ssl=true``` on connectionString and works =D

Thk's for help @robconery

**Comment by rcalabro** [comment]
Thank you @aderbas !!

**Comment by odupuy** [comment]
If you want to go further, either rejecting a self-signed certificate from the server (accepted by default) or implementing mutual authentication with certificates on both sides, look at https://github.com/brianc/node-postgres/wiki/SSL-support for an example of the configuration to use.
Either you use ?ssl=true or you use the ssl property of the configuration object but not both.
