### ISSUE TITLE
Test discrepancies between 9.4 and 9.5

### ISSUE THREAD

**Issue by robinjmurphy** [robconery/massive-js#189]
I'm not sure if there's a plan to support one or both of 9.4 and 9.5?

When running the tests against 9.4 there are two failures.

```
  1) Document updates, Save data and update, updates the document:
     Uncaught TypeError: Cannot read property 'vaccinated' of null
      at Object.next (test/document_update_spec.js:30:25)
      at Object.next (lib/document_table.js:131:12)
      at null.callback (lib/runner.js:53:16)
      at Query.handleError (node_modules/pg/lib/query.js:106:17)
      at null.<anonymous> (node_modules/pg/lib/client.js:171:26)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  2) Document updates, Save data and update, updates the document without replacing existing attributes:
     Uncaught TypeError: Cannot read property 'score' of null
      at Object.next (test/document_update_spec.js:37:25)
      at Object.next (lib/document_table.js:131:12)
      at null.callback (lib/runner.js:53:16)
      at Query.handleError (node_modules/pg/lib/query.js:106:17)
      at null.<anonymous> (node_modules/pg/lib/client.js:171:26)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

When running the tests against 9.5 there are two different failures.
```
  1) On spin up loads up functions:

      AssertionError: 21 == 20
      + expected - actual

      -21
      +20
      
      at Context.<anonymous> (test/loader_spec.js:31:12)

  2) Synchronous Load loads up functions:

      AssertionError: 21 == 20
      + expected - actual

      -21
      +20
      
      at Context.<anonymous> (test/loader_spec.js:64:12)
```

Would be good to get the tests passing against one or both of the versions.

**Comment by xivSolutions** [comment]
@robconery may have some specifics to add, but I think we may need to find a way to support both. 

I also think there are some features in 9.5 worth taking advantage of ("upsert" being one of them). 

I hope to dig in and see what's what with 9.5 this weekend. 

That second test looks like it's simply not finding all of the functions to load. May or may not be related to the version change.

**Comment by robinjmurphy** [comment]
Might be possible to run some tests conditionally depending on the version of Postgres? Then it's just a case of clearly documenting what's supported in each version. Would definitely be good to take advantage of upsert whilst maintaining support for 9.4.

**Comment by xivSolutions** [comment]
@robinjmurphy My thoughts precisely, on all points.
