### ISSUE TITLE
findOne doesn't support query options

### ISSUE THREAD

**Issue by riteshsangwan** [robconery/massive-js#272]
As per the documentation [here](http://massive-js.readthedocs.io/en/latest/simple_queries/#using-find-and-findone) findOne supports query options.

I am calling findOne function like

```
const columns = ['company_name', 'created_at', 'created_by', 'email_domain', 'id', 'logo_url',
                  'modified_at', 'modified_by', 'stats', 'time_zone'];
db.companies.findOne(companyId, { columns: columns }, callback);
```

And I got an error

```
TypeError: next is not a function
    at Object.next (/Users/sabertooth/projects/compete/topcoder/30054518/waterworks/node_modules/massive/lib/queryable.js:55:7)
    at null.<anonymous> (/Users/sabertooth/projects/compete/topcoder/30054518/waterworks/node_modules/massive/lib/runner.js:67:14)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Query.handleReadyForQuery (/Users/sabertooth/projects/compete/topcoder/30054518/waterworks/node_modules/pg/lib/query.js:89:10)
    at null.<anonymous> (/Users/sabertooth/projects/compete/topcoder/30054518/waterworks/node_modules/pg/lib/client.js:163:19)
    at emitOne (events.js:95:20)
    at emit (events.js:182:7)
    at Socket.<anonymous> (/Users/sabertooth/projects/compete/topcoder/30054518/waterworks/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

So I dig into the code and came to know about this statement

https://github.com/robconery/massive-js/blob/master/lib/queryable.js#L34-L53

there I can see that the error is valid. So the documentation should be updated or function should supports query options

**Comment by robconery** [comment]
It really should support query options :). Thank you for this report ... if you're open to doing a PR that would be ultra helpful, other than that I'll dig in when I can.

**Comment by dmfay** [comment]
whoops. Everything's good now though.
