### ISSUE TITLE
Error: null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by digitalysin** [robconery/massive-js#307]
products table
  id : primary key , auto inc, not null
  name: text

```javascript
db.products.insert([ { name: "P1" }, { name: "P2" }], (error, rows) => {

})
```

got this error

```javascript
{ Error: null value in column "id" violates not-null constraint
    at DB.query (/Users/h/Documents/j/p/node_modules/massive/lib/runner.js:22:11)
    at Table.insert (/Users/h/Documents/j/p/node_modules/massive/lib/table.js:45:11)
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:503:10)
  message: 'null value in column "id" violates not-null constraint',
  code: '23502',
  detail: 'Failing row contains (null, 10, null, null, null, null, null, null).',
  length: 202,
  severity: 'ERROR',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'products',
  column: 'id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1699',
  routine: 'ExecConstraints' }
```

**Comment by xivSolutions** [comment]
Do the existing tests run? There is a test in the `tests/table_spec.js` file that does this very thing. Would be helpful to know if that test file runs correctly, or if the test fails as well. From the looks of things, your code seems like it should be working. 

Also, could you show us the *exact* `create` script for your table?

**Comment by digitalysin** [comment]
my mistake, forgot to add sequence.
