### ISSUE TITLE
Cannot read property 'insert' of undefined

### ISSUE THREAD

**Issue by AlexZeitler** [robconery/massive-js#94]
I created a few `.sql` files:

`createcustomerstable.sql`

````sql
BEGIN;
DROP TABLE IF EXISTS customer;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS Customer (
  ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  CompanyName1 VARCHAR(40),
  CreatedAt DATE DEFAULT now()
);
END;
````

`seedcustomertable.sql`

````sql
INSERT INTO public.customer (companyname1) VALUES ('GitHub');
````

Then I created a little app:

`app.js`

````js
var express = require("express");
var app = express();
var http = require('http');
var massive = require("massive");
var connectionString = "postgres://postgres:postgres@localhost/postgres";
var bodyParser = require("body-parser");

var massiveInstance = massive.connectSync({connectionString: connectionString});
app.set('db', massiveInstance);

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

var db = app.get('db');
db.createcustomerstable(function(err, res) {
    db.seedcustomertable(function(err, res) {
    });
});

app.post('/api/customers', function(request, response) {
    var db = app.get('db');
    var customer = request.body;
    db.customer.insert(customer, function(error, newCustomer) {
            response.status(201).json(newCustomer)
    })
});
````

Then I created a test:

`test.js`

````js
var request = require('supertest');
var app = require('../app.js');
var assert = require("assert");

describe('POST /api/customers/', function () {
    it('responds with customers', function (done) {

        var customer = { companyname1 : "Microsoft"}

        request(app).post('/api/customers/')
            .set('Content-type', 'application/json; charset=utf-8')
            .send(customer)
            .expect(function (res) {
                assert.equal(res.body.companyname1,'Microsoft');
            })
            .end(done)
    });
});
````

Running the test results in:

````bash
TypeError: Cannot read property 'insert' of undefined
    at /home/alex/src/hellomassive/customerservice/app.js:55:16
    at Layer.handle [as handle_request] (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/layer.js:95:5)
    at /home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:330:12)
    at next (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/alex/src/hellomassive/customerservice/node_modules/body-parser/lib/types/urlencoded.js:81:44)
    at Layer.handle [as handle_request] (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:312:13)
    at /home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:330:12)
    at next (/home/alex/src/hellomassive/customerservice/node_modules/express/lib/router/index.js:271:10)
    at /home/alex/src/hellomassive/customerservice/node_modules/body-parser/lib/read.js:121:5
    at done (/home/alex/src/hellomassive/customerservice/node_modules/body-parser/node_modules/raw-body/index.js:239:14)
    at IncomingMessage.onEnd (/home/alex/src/hellomassive/customerservice/node_modules/body-parser/node_modules/raw-body/index.js:285:7)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
````

If I run the test again, it works.
When deleting the table `customer` and repeating the steps shown above again, it fails - re-run all is ok.

**Comment by dmfay** [comment]
Yeah, I ran into a similar thing -- Massive loads up your tables on connect, so when you create the tables _after_ connecting they don't have the methods attached. The second time, since you already have the schema leftover, it works fine.

What I ended up doing is connecting once to make schema changes and then reconnecting. It worked out fine for me since I'm doing it in a grunt task and can muck around with schema as a superuser before reconnecting as the app user to seed the data, although I can see where a 'reload configuration' option might be useful in other situations.

**Comment by AlexZeitler** [comment]
Thanks, that approves my apprehension. 
AFAIK @robconery is not a friend of handling schema stuff / changes inside the application so that massive behavior makes even more sense.

As I'm already using `.sql` files I think I'll run them using `psql` upfront or I'll place them in my `Dockerfile`.

Thanks again :+1:

**Comment by xivSolutions** [comment]
in a sample app I was putting together, I made just added an configure.js file which I used to do this type of thing, left it at the project root next to index.js.

**Comment by robconery** [comment]
I've been doing this (loading schema after connect) and I just rerun `connect` which loads up the changes. Would that help?
